jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  atk-expiration-seconds: ${JWT_ATK_EXPIRATION_SECONDS}

logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off