ALTER TABLE blog
    MODIFY link VARCHAR(600) NOT NULL,
    MODIFY logo_url VARCHAR(600) NULL,
    MODIFY rss_link VARCHAR(600) NOT NULL;

ALTER TABLE article
    MODIFY link VARCHAR(600) NOT NULL,
    MODIFY guid VARCHAR(600) NULL;