spring:
  application:
    name: app

  config:
    import: optional:file:.env[.properties]

  profiles:
    include:
      - infra-oauth
    group:
      local:
        - local
        - infra-db-local
        - infra-jwt-local
      prod:
        - prod
        - infra-db-prod
        - infra-jwt-prod

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health