spring:
  application:
    name: app

  config:
    import: optional:file:.env[.properties]

  profiles:
    include:
      - infrastructure-oauth
    group:
      local:
        - local
        - infrastructure-mysql-local
        - infrastructure-jwt-local
        - infrastructure-jpa-local
        - infrastructure-kafka-local
      prod:
        - prod
        - infrastructure-mysql-prod
        - infrastructure-jwt-prod
        - infrastructure-jpa-prod
        - infrastructure-kafka-prod

management:
  endpoints:
    web:
      exposure:
        include: prometheus, heal